### ISSUE TITLE
Cant list/see/install packages via Docker container

### ISSUE THREAD

**Issue by Awia00** [loic-sharma/BaGet#83]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
Reproduction steps

- I clone the repository, 
- Then run `docker build . -t baget` 
- Then create `baget.env` file according to the wiki.
- Then `docker run --rm --name nuget-server -p 5555:80 --env-file baget.env -v "$(pwd)/baget-data:/var/baget" baget:latest`. The container starts up without any error messages.
- Then i try to push a nuget package I have with: `dotnet nuget push -s http://localhost:5555/v3/index.json -k NUGET-SERVER-API-KEY AccountReconciliation.RestAPI.Client.0.1.2.nupkg` which results in: 
```
info : Pushing AccountReconciliation.RestAPI.Client.0.1.2.nupkg to 'http://localhost:5555/v2/package'...
info :   PUT http://localhost:5555/v2/package/
info :   Created http://localhost:5555/v2/package/ 343ms
info : Your package was pushed.
```

### What did you expect to see?
I expect the website to show the pushed package. I expect `nuget list -s http://localhost:5555` to show `AccountReconciliation.RestApi.Client.0.1.2` and `nuget install AccountReconciliation.RestApi.Client` to download and install the package into my project.

### What did you see instead?

When I enter http://localhost:5555 there are no packages shown. 
If i try to run `nuget list -s http://localhost:5555` I get 
`WARNING: The remote server returned an error: (404) Not Found.
No packages found.`. 
If I try to install with: `nuget install AccountReconciliation.RestAPI.Client -Source http://localhost:5555` I get 
`WARNING: An error occurred while loading packages from 'http://localhost:5555/': The remote server returned an error: (404) Not Found.
WARNING: An error occurred while loading packages from 'http://localhost:5555/': The remote server returned an error: (404) Not Found.
Unable to find package 'AccountReconciliation.RestAPI.Client'.`

### Output of `git rev-parse HEAD`: (_What version of BaGet are you using?_)

```
e9ebce2bd390796f266a747db40619095750249c
```

### What is your environment & configuration (arguments, platform, ...)?
Ubuntu 18.04
Docker version 18.06.0-ce, build 0ffa825

### If applicable, please paste the log output in DEBUG level
Dont know what to show but docker log [containerid] shows the following:
```
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {23774c5d-d43b-45a9-a87b-a08b59324403} may be persisted to storage in unencrypted form.
Hosting environment: Development
Content root path: /app
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
```

**Comment by loic-sharma** [comment]
Thank you for reporting these issues!

> When I enter http://localhost:5555 there are no packages shown.

This is a bug in the generated frontend. I will fix this ASAP. As a temporary work around, running the docker image as this should fix the UI issue: `docker run --rm --name nuget-server -p 50561:80 --env-file baget.env -v "$(pwd)/baget-data:/var/baget" baget:latest`.

> If i try to run nuget list -s http://localhost:5555 I get
`WARNING: The remote server returned an error: (404) Not Found. No packages found..`

> If I try to install with: nuget install AccountReconciliation.RestAPI.Client -Source http://localhost:5555 I get
`WARNING: An error occurred while loading packages from 'http://localhost:5555/': The remote server returned an error: (404) Not Found. WARNING: An error occurred while loading packages from 'http://localhost:5555/': The remote server returned an error: (404) Not Found. Unable to find package 'AccountReconciliation.RestAPI.Client'.`

I believe that these NuGet commands are using v2 APIs, which BaGet does not support. I'll look into what it takes to add support for these commands. Can you install packages using `dotnet restore` instead?

**Comment by Awia00** [comment]
Thanks for the swift response! I think it is really awesome what you are doing here with BaGet!

Ill try out dotnet restore tonight. Do you know if there is a way to list packages on source with v3 CLI or a way to get `nuget install/push/whatever` to use v3?

**Comment by loic-sharma** [comment]
Yup, like @smazurov  said, you should be able to use most commands so long as `http://locahost:5555/v3/index.json` is your source. For example:

* `nuget push newtonsoft.json.nupkg -Source http://localhost:5555/v3/index.json`
* `nuget install newtonsoft.json -Version 11.0.2 -Source http://localhost:5555/v3/index.json`

Some caveats:

* The `nuget list` command does not work on BaGet.
* Ensure your NuGet client is a recent version. Old versions of NuGet use protocols that are not supported by BaGet

Also, the search UI should be fixed by: https://github.com/loic-sharma/BaGet/commit/ed0e62d3bdf29aecc4edbfb1f2a48e140769165c

@Awia00 Could you verify that everything except `nuget list` list working as expected?

**Comment by Awia00** [comment]
Frontend is working :+1: 

`nuget install AccountReconciliation.RestAPI.Client -Source http://localhost:5555/v3/index.json` still fails with 404, but `dotnet add AccountReconciliation.RestAPI.Client` works.

This means that BaGet fulfills my use cases! It would of course be preferable if the `nuget` commands (list/install and so on) also worked, but again I can do without.

Thanks for the help!

**Comment by loic-sharma** [comment]
Sweet!

I’m surprised that `NuGet install` doesn’t work - what version of NuGet are you using?

**Comment by Awia00** [comment]
The version on apt-get which seems to be NuGet Version: 2.8.7.0
That could explain the results I'm getting. Seems like they do not update that version.
As far as I can see I have to install mono and install a nuget version specific to that?

**Comment by loic-sharma** [comment]
Yup, that would be it - NuGet 2.8 is very old. If you’re on macOS I would recommend you use the dotnet CLI if possible.

As that was the last bug that needed addressing, I’ll go ahead and close off this issue. Feel free to open another issue if you run into anything else!
